### ISSUE TITLE
Titleize feature names

### ISSUE THREAD

**Issue by banczi** [SOFTWARE-CLINIC/featurebook#12]
A feature name displayed in the navigation tree is inferred from the corresponding Gherkin source file name, i.e. it's a titleized base file name. For example, list_users.feature becomes List Users.

**Comment by danielpacak** [comment]
@banczi to make your life easier and simplify merge, I've already create an Angular filter placeholder for you:

https://github.com/SOFTWARE-CLINIC/featurebook/blob/master/public/assets/js/titleize.filter.js.

You implementation should go there. There is also a unit test for this filter:

https://github.com/SOFTWARE-CLINIC/featurebook/blob/master/test/public/spec/titleize.filter.spec.js

Now it's failing, but should pass once you're done with the homework ;)
