### ISSUE TITLE
alt+s (ś) not working in edit spec mode

### ISSUE THREAD

**Issue by waxxfetish** [SOFTWARE-CLINIC/featurebook#39]

**Comment by danielpacak** [comment]
This seems to be an [issue](https://github.com/ajaxorg/ace/issues/2541) with Ace editor itself. We're using buggy 1.1.9 and they promise to fix it in 1.2.0. Let's keep this open to track the release and upgrade on our side.

**Comment by danielpacak** [comment]
I removed the ace editor from the current version of featurebook. Editing features is more complicated than just adding editor's div and highlighting Gherkin syntax. It should be implemented from scratch; probably as a plugin with VCS integration.
