### ISSUE TITLE
[Generator] HTML

### ISSUE THREAD

**Issue by danielpacak** [SOFTWARE-CLINIC/featurebook#47]
``` gherkin
Feature: `html` command

  Background:
    Given a directory with Gherkin source files

  Scenario: Generate HTML specification in the default output directory
    When I run `featurebook html`
    Then I can access specification HTML at "dist/html/specification.html"

  Scenario: Generate HTML specification in the given output directory
    When I run `featurebook html --output-dir target/docs`
    Then I can access specification HTML at "target/docs/specification.html"
```

**Comment by spinus** [comment]
+1

**Comment by sergeyshushlyapin** [comment]
+1

**Comment by mattaylor** [comment]
+1

**Comment by danielpacak** [comment]
A short update here. In v0.0.28 the HTML generator is actually implemented. It lacks SUMMARY.md handling and does not support Markdown syntax yet but's it's a work in progress. I have to refactor some Markdown parsing code first to close this issue.

![featurebook-html](https://cloud.githubusercontent.com/assets/1322923/13905432/bca81356-eebf-11e5-8fc8-48cad41b5760.png)

**Comment by danielpacak** [comment]
This is fully operational in v0.0.29. Due to modules refactoring I need to cleanup CSS and probably share it between featurebook-serve and featurebook-html modules.

![featurebook_screenshot_1](https://cloud.githubusercontent.com/assets/1322923/14767410/9ba5c628-0a24-11e6-96e0-63f3f3bae01a.png)

**Comment by danielpacak** [comment]
Closing this one. Any improvements should be handled as dedicated issues.
