### ISSUE TITLE
Generated HTML is empty

### ISSUE THREAD

**Issue by wmbenedetto** [SOFTWARE-CLINIC/featurebook#54]
Running "featurebook html" generates an empty specification.html file, and nothing else.

Also, it seems to ignore the output directory -- no matter what I put, it always puts it in ./dist/html.

FWIW, running "featurebook pdf" works perfectly.

**Comment by danielpacak** [comment]
@wmbenedetto thank you for reporting this. Indeed there was an issue with parsing the outputDir option for the html command. However the HTML output generator implementation is not finished yet. I track it in #47 and I'll close it soon.
