### ISSUE TITLE
bower + git:// + npm postinstall failure

### ISSUE THREAD

**Issue by waxxfetish** [SOFTWARE-CLINIC/featurebook#7]
`bower install` fails when executed via postinstall script, within environments without git:// protocol access

**Comment by waxxfetish** [comment]
dirty `package.json` workaround: 

```json
//...
 "scripts": {
    "postinstall": "cd public && git config --global url.\"https://\".insteadOf git:// && bower install"
  },
//...
```

**Comment by danielpacak** [comment]
Sadly there are some other issues even if we have access to git:// protocol:
 1. First of all Travis CI doesn't like this `postinstall` script. No idea why???
 2. On top of that we cannot assume that everyone has `bower` installed globally. One option is to add it to `package.json` as dependency and refer to `bower` as `./node_modules/bower/bin/bower`.

I'd suggest experimenting with bower on a dedicated branch to make `master` stable and finish other functional issues for release v1.0.0.

For the time being I'll get rid of the `postinstall` script, commit JavaScript dependencies referred to by index.html, and release something that's actually working.

**Comment by danielpacak** [comment]
We should not run `bower install` as a post install script (I've already changed that). It will require end users to have bower and some git client installed. We target non technically inclined users.
